excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - submodules
  - vendor/bundle
  - Carthage
disabled_rules:
- identifier_name
- function_body_length
- function_parameter_count
- type_body_length
- trailing_comma
